# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=1000)),
                ('roll_num', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('aggregate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
